### ISSUE TITLE
Optionally wait until SLC is deployed to all nodes in the database cluster

### ISSUE THREAD

**Issue by ckunki** [exasol/python-extension-common#42]
```[tasklist]
### Tasks
- [ ] https://github.com/exasol/python-extension-common/issues/50
- [ ] https://github.com/exasol/python-extension-common/issues/49
- [ ] https://github.com/exasol/python-extension-common/issues/51
- [ ] https://github.com/exasol/python-extension-common/issues/52
- [ ] https://github.com/exasol/python-extension-common/issues/48
- [ ] https://github.com/exasol/python-extension-common/issues/53
```

**Comment by ckunki** [comment]
Question: Should it be possible to call `LanguageContainerDeployer.upload_container()` without `run()`?

The old implementation calculated the final destination path inside public method `upload_container()` 

In order to validate complete extraction on all cluster nodes, the final destination path needs to be calculated once again. 

So I prefer to 
* either change the signature of method `upload_container()` to put in the final destination path
* or move the validation inside method `upload_container()`
* In the second case, the boolean flag `wait_for_completion` needs to be forwarded to method `upload_container()`, hence another change to the method's signature.

**Comment by ckunki** [comment]
Closing ticket in favor of the Subtasks
